### ISSUE TITLE
gulp-riot exists with "Cannot read property 'brackets' of undefined"

### ISSUE THREAD

**Issue by juriansluiman** [e-jigsaw/gulp-riot#42]
Not sure what to give you for info, but haven't used the project for a while and now I get a TypeError. Cmd output:

``` cmd
vagrant@jurian2:/vagrant$ gulp scripts
[20:00:34] Using gulpfile /vagrant/gulpfile.js
[20:00:34] Starting 'scripts'...
[20:00:34] Finished 'scripts' after 21 ms

undefined:43
  var brackets = riot.util.brackets
                          ^
TypeError: Cannot read property 'brackets' of undefined
    at compileHTML (eval at <anonymous> (/vagrant/node_modules/gulp-riot/node_modules/riot/lib/server/compiler.js:8:20), <anonymous>:43:27)
    at eval (eval at <anonymous> (/vagrant/node_modules/gulp-riot/node_modules/riot/lib/server/compiler.js:8:20), <anonymous>:214:7)
    at String.replace (native)
    at compile (eval at <anonymous> (/vagrant/node_modules/gulp-riot/node_modules/riot/lib/server/compiler.js:8:20), <anonymous>:186:14)
    at DestroyableTransform.transform [as _transform] (/vagrant/node_modules/gulp-riot/build/index.js:15:32)
    at DestroyableTransform.Transform._read (/vagrant/node_modules/gulp-riot/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/vagrant/node_modules/gulp-riot/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/vagrant/node_modules/gulp-riot/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/vagrant/node_modules/gulp-riot/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at DestroyableTransform.Writable.write (/vagrant/node_modules/gulp-riot/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:211:11)
```

Relevant gulp part:

``` js
gulp.src(['node_modules/riot/riot.js', 'public/scripts/src/*.tag'])
    .pipe(gulpif('*.tag', riot()))
    .pipe(gulpif(argv.production, uglify()))
    .pipe(concat('riot.js'))
    .pipe(chmod(644))
    .pipe(gulp.dest('public/scripts/dist'));
```

My `*.tag` files seems pretty simple, not sure if that might be the problem.

My `package.json`:

``` js
{
  "name": "juriansluiman.nl",
  "version": "2.0.0-alpha1",
  "dependencies": {
    "gulp": "^3.8.10",
    "gulp-chmod": "^1.2.0",
    "gulp-concat": "^2.4.3",
    "gulp-if": "^1.2.5",
    "gulp-minify-css": "^0.3.11",
    "gulp-riot": "^0.2.0",
    "gulp-uglify": "^1.0.2",
    "gulp-watch": "^4.1.0",
    "humane-js": "^3.2.2",
    "lodash": "^3.6.0",
    "medium-editor": "^4.0.0",
    "normalize.css": "^3.0.3",
    "prismjs": "git://github.com/PrismJS/prism",
    "riot": "^2.0.14",
    "skeleton.css": "^1.1.0",
    "yargs": "^3.7.1"
  }
}
```

Let me know if this is a gulp-riot issue or not, and if you need more info,

**Comment by e-jigsaw** [comment]
@juriansluiman I published `gulp-riot@0.2.17` . It contains riot updates. Could you upgrade and check again?

**Comment by juriansluiman** [comment]
@e-jigsaw removed `./node_models`, cleared the npm cache and did an install (which installed 0.2.17) but problem is still there.

It seems it's a problem in ./node_modules/gulp-riot/node_modules/riot/lib/server/compiler.js:8:20, which is riot.js itself. Let me post an issue on their tracker as well to make sure it's not part of gulp-riot.

**Comment by juriansluiman** [comment]
I should test before I shout...

When I install riot globally (`npm install -g riot`) and let riot compile any of my `*.tag` files, all goes well. So apparently it is not within riot but the integration part between riot and gulp. @e-jigsaw any suggestions where I can look at to help debugging?

**Comment by e-jigsaw** [comment]
@juriansluiman fmm...

Could you show me `.tag` file? I checked your codes:

`package.json`:

```
{
  "name": "juriansluiman.nl",
  "version": "2.0.0-alpha1",
  "dependencies": {
    "gulp": "^3.8.10",
    "gulp-chmod": "^1.2.0",
    "gulp-concat": "^2.4.3",
    "gulp-if": "^1.2.5",
    "gulp-minify-css": "^0.3.11",
    "gulp-riot": "^0.2.0",
    "gulp-uglify": "^1.0.2",
    "gulp-watch": "^4.1.0",
    "humane-js": "^3.2.2",
    "lodash": "^3.6.0",
    "medium-editor": "^4.0.0",
    "normalize.css": "^3.0.3",
    "prismjs": "git://github.com/PrismJS/prism",
    "riot": "^2.0.14",
    "skeleton.css": "^1.1.0",
    "yargs": "^3.7.1"
  }
}
```

`gulpfile.js`:

```
var gulp = require('gulp');
var gulpif = require('gulp-if');
var riot = require('gulp-riot');
var concat = require('gulp-concat');
var chmod = require('gulp-chmod');

gulp.task('script', function(){
  gulp.src(['node_modules/riot/riot.js', 'src/*.tag'])
    .pipe(gulpif('*.tag', riot()))
    .pipe(concat('riot.js'))
    .pipe(chmod(644))
    .pipe(gulp.dest('public/scripts/dist'));
});
```

`src/todo.tag` (this is riot's sample):

```
<todo>

  <!-- layout -->
  <h3>{ opts.title }</h3>

  <ul>
    <li each={ item, i in items }>{ item }</li>
  </ul>

  <form onsubmit={ add }>
    <input>
    <button>Add #{ items.length + 1 }</button>
  </form>

  <!-- logic -->
  <script>
    this.items = []

    add(e) {
      var input = e.target[0]
      this.items.push(input.value)
      input.value = ''
    }
  </script>

</todo>
```

```
✈ gulp script
[12:15:32] Using gulpfile ~/tmp/gulp-riot-test/gulpfile.js
[12:15:32] Starting 'script'...
[12:15:32] Finished 'script' after 23 ms
✈ cat public/scripts/dist/riot.js
...
(riot codes)
riot.tag('todo', ' <h3>{ opts.title }</h3> <ul> <li each="{ item, i in items }">{ item }</li> </ul> <form onsubmit="{ add }"> <input> <button>Add #{ items.length + 1 }</button> </form> ', function(opts) {
    this.items = []

    this.add = function(e) {
      var input = e.target[0]
      this.items.push(input.value)
      input.value = ''
    }.bind(this);

});
```

It works.

**Comment by juriansluiman** [comment]
``` diff
--- a/gulpfile.js
+++ b/gulpfile.js
var argv   = require('yargs').argv,
     gulp   = require('gulp'),
-    concat = require('gulp-concat');
+    concat = require('gulp-concat'),
     minify = require('gulp-minify-css'),
     uglify = require('gulp-uglify'),
     riot   = require('gulp-riot'),
     chmod  = require('gulp-chmod'),
     watch  = require('gulp-watch')
     gulpif = require('gulp-if');
```

![You simply cannot be that stupid](https://i.imgflip.com/oqv7y.jpg)

Sorry about your time... It just wasn't working and you couldn't figure out because I didn't provide the full example (and what I showed, wasn't tested by me).

**Comment by e-jigsaw** [comment]
:sob:
